### ISSUE TITLE
Deliverable: P1 Demo

### ISSUE THREAD

**Issue by th7nder** [eigerco/polka-storage#111]
The goal of this deliverable is to deliver to the community artifacts and documentation which will show-off our work and prove that we're solid and capable developers.

Quality is more important then __when__, but let's start gathering those things to be able to discuss them internally first and show our progress.

Ideal P1 package :
- [x] #209  
    - Documentation and description what we have achieved so far
    - Storage Provider Node (off-chain), [someone] to write about that:
        - RPC skeleton and integration with on-chain node 
        - Implemented File Storage: FileStore/PieceStore
            - Implemented CAR v2 library for handling files as there was none on the market 
        - DEMO: RPC with uploading a file and downloading created CARv2 archive [someone]
        - ... not exhaustive
    - Parachain Implementation [someone] to write about that:
        - Configured Parachain as system parachain to be able to use native tokens as currency
        - Figured out how the Collators should produce blocks, with major differences to the FileCoin
        - Configured relevant ready-made pallets (collator-selection, balances, etc. ) to support our parachain.
        - Implemented Market business on-chain use cases, like: publishing deals, activating deals, slashing and terminating deals
        - Implemented Storage Provider use cases: registering providers, pre-committing sectors, proving sectors, terminating sectors, slashing Storage Providers
        - Write about the flow end-2-end and provide proof/screenshots that it works.
- [x] Docker image/compiled demo (something to run)
    - [x] #114  
        - [X] Document the usage.
    - [x] #116 
        - [x] Document the usage.
- [x] #110 
- [x] #127 

- [x] #259 
    -  At the very end: Video Recording to prove it works (calling extrinsics, showing events, etc) [someone]
