### ISSUE TITLE
Market Pallet: Phase 3

### ISSUE THREAD

**Issue by th7nder** [eigerco/polka-storage#162]
## Phase 2 (Done)
- [x] ~#92 — CommD Port~ (part of the proofs)
- [x] #87 — Storage Provider Validation

## Phase 3
- [x] Run the benchmarks and configure weights (#77)
- [x] Take it out of the dev mode (#77)
- [x] #121

From #11

**Comment by th7nder** [comment]
It's done (as of original scope).
