### ISSUE TITLE
[Tracking] P1.5 Issues

### ISSUE THREAD

**Issue by th7nder** [eigerco/polka-storage#272]
- [x] #279
- [x] #280
- [x] #277 
- [x] #278
- [x] #281 
- [x] #285 
- [x] after the deal has ended, the SP is still slashed, but this is probably due to #109 
![image](https://github.com/user-attachments/assets/10112554-bd0b-4b12-a2aa-8ac7742832cc)
- [x] how does the storage provider get the information when his proving period starts? currently needs to query the chain state. (simple, via #271)
- [x] emitting DealSlashed (after pre-commit)event with dealId: number is not useful to the user at all, as they can't even list the published deals at this point? (simple, via #271)

can live without:

to be continued...
