### ISSUE TITLE
[Docs]: Tracking for P2

### ISSUE THREAD

**Issue by jmg-duarte** [eigerco/polka-storage#506]
Following is a list of issues with the current documentation. 

Create issues as you go, one point may not be enough for an issue, that's ok, just open one that covers multiple.

- [x] #541
  - [x] Still refers to P1
  - [x] Integrate P2 delivery, while keeping relevant parts from P1
- [x] Architecture
  - [x] #533
  - [x] #531
  - [x] #539
  - [x] ~Link to the file upload demo as "next steps"~ the book structure implies this
- [x] Getting Started
  - [x] Missing chapters — i.e. there are links on the file that point to pages that are not chapters
  - [x] #517
    - [x] #513 
  - [x] #535
- [x] Polka Storage Provider CLI
  - [x] #530
  - [x] #515
- [x] #509
  - [x] Cover the newest changes
    - [x] Randomness (if exists in the CLI)
    - [x] #546
    - [x] `--wait-for-finalization`
  - [x] Review the CLI interface for "ergonomic improvements"
- [x] #507
  - [x] Add file conversion example
  - [x] Explain how to validate our conversion using `go-car`
- [x] Pallets
  - [x] #528
  - [x] #520
  - [x] #526
- [x] #549
- [x] #544
  - [x] Remove the demo.md
