### ISSUE TITLE
[tracking] address feedback from Polkadot forum

### ISSUE THREAD

**Issue by jmg-duarte** [eigerco/polka-storage#606]
Forum comment: https://forum.polkadot.network/t/polkadot-native-storage-updates/7021/44

🚒 Urgent
- [x] Errors exposed to the user are not informative (WIP already, but not done yet) - #599 
- [ ] The docs are still being improved and, in the current iteration, may be confusing (in short, installation/setup workflow is confusing — *needs more info*
- [x] The docs are out of sync with the repo, which made me waste 1-2 hours until I discovered that). This will be improved as well. Binaries/containers are out of sync with the docs as well (e.g. the faucet command) — docs are ahead, we need to rebuild the binaries
- [x] The repo defaults to develop but the docs refer to releases and some PRs with fixes don’t have useful recent commits, while latest release (and therefore, containers) has a 3 week old release) — write a banner in the README stating that `main` has the "stable" build
- [x] Publish deal RPC error is confusing — #607

⚠️ Important
- [x] More info about max size of blobs that can be PUT
- [x] GET steps (there are none, but we need to document that)
- [x] I wonder if there will be a way to differentiate public vs. private access
- [x] Recommended approach to encrypt objects, in the case public access be the default (I can’t tell if it will or won’t, since GET step isn’t in the docs right now)
- [x] It’s not very clear - although it didn’t impact my evaluation - if it’s OK to submit and sign a proposal before start_block as long as it’s not published before it. I wouldn’t expect that PUT can be performed before start_block, but maybe other steps can although, even in that case, the question is how much before start_block (i.e. N-14400, N-256, etc.)
