### ISSUE TITLE
[Tracking] libp2p Peer ID to mulitaddr resolver

### ISSUE THREAD

**Issue by aidan46** [eigerco/polka-storage#627]
This tracking issue is for the application that resolves Peer ID registered to the storage provider on-chain to multiaddrs that are used by the polka-fetch component to fetch files from said storage provider.
This tracking issue is a work in progress, once the RFC has. been accepted the tracking issue will be expanded to include implementation and testing issues.

- [x] RFC for libp2p Peer ID to multiaddr resolver #628 -> #629
- [x] Implement resolver bootstrap and registration node into storage provider server #652 -> #666 
- [x] Implement public key to Peer ID conversion #667 -> #666 
- [x] Update rpc_publish to include p2p change #668 -> #666 
- [x] Add re-registration for p2p node #682 -> #685 
- [x] Update docs after p2p node integration #676 -> #686 
- [x] Add p2p discovery example #687  
- [x] Have `NodeType` hold node variables #677 
- [x] RFC for P2P information exchange improvement #714
- [x] Move P2P bootstrap into collator #720 -> #727 
- [x] Implement P2P info exchange improvement #715
